### ISSUE TITLE
Offer to become a Maintainer

### ISSUE THREAD

**Issue by drybro** [backdrop-contrib/adaptive_image#8]
I would like to become a maintainer for this project.

**Comment by jenlampton** [comment]
@drybro I have marked this project as abandoned since the original maintainer had not responded to https://github.com/backdrop-contrib/adaptive_image/issues/5. 

As soon as your maintainer application has been approved we should be able to add you here right away, no need to wait the standard 2-weeks. 

Please file a PR adding your name to the README, and we'll be able to merge that as soon as you get access.

**Comment by drybro** [comment]
A README file change was done and it got combined with the existing PR to fix the typo causing a 500 error. Have  unsuccessfully tried to separate the README change into it's own PR. In the mean time this bug still exists and I don't have merge or write access to the module to fix the problem.

**Comment by herbdool** [comment]
@drybro I've merged the PR on behalf of the @backdrop-contrib/bug-squad and given you permission to maintain the project. And made a new bug fix release. From now on you're the maintainer.
